/**
 * hlquery Node.js Client - Server conformance manifest
 *
 * This manifest maps routed server endpoints to the Node client wrapper that
 * owns them. Any server route in scope must be marked as supported or omitted.
 */

const NODE_CLIENT_ROUTE_COVERAGE = [
    { path: '/', methods: ['GET'], status: 'supported', client: 'system.info' },
    { path: '/health', methods: ['GET'], status: 'supported', client: 'system.health' },
    { path: '/status', methods: ['GET'], status: 'supported', client: 'system.status' },
    { path: '/startup', methods: ['GET'], status: 'supported', client: 'system.startup' },
    { path: '/boot-status', methods: ['GET'], status: 'supported', client: 'system.bootStatus' },
    { path: '/stats', methods: ['GET'], status: 'supported', client: 'system.stats' },
    { path: '/metrics', methods: ['GET'], status: 'supported', client: 'system.metrics' },
    { path: '/metrics.json', methods: ['GET'], status: 'supported', client: 'system.metricsJson' },
    { path: '/metrics/history', methods: ['GET'], status: 'supported', client: 'system.metricsHistory' },
    { path: '/metrics-history', methods: ['GET'], status: 'supported', client: 'system.metricsHistoryAlias' },
    { path: '/connections', methods: ['GET'], status: 'supported', client: 'system.connections' },
    { path: '/rocksdb', methods: ['GET'], status: 'supported', client: 'system.rocksdb' },
    { path: '/_rocksdb', methods: ['GET'], status: 'supported', client: 'system.rocksdbInternal' },
    { path: '/doctotal', methods: ['GET'], status: 'supported', client: 'system.docTotal' },
    { path: '/etc', methods: ['GET'], status: 'supported', client: 'system.etc' },
    { path: '/ping', methods: ['GET'], status: 'supported', client: 'system.ping' },
    { path: '/integrity', methods: ['GET'], status: 'supported', client: 'system.integrity' },
    { path: '/consistency', methods: ['GET'], status: 'supported', client: 'system.consistency' },
    { path: '/self-check', methods: ['GET'], status: 'supported', client: 'system.selfCheck' },
    { path: '/admin/storage_status', methods: ['GET'], status: 'supported', client: 'system.storageStatus' },
    { path: '/config-files', methods: ['GET'], status: 'supported', client: 'system.configFiles' },
    { path: '/cache', methods: ['GET'], status: 'supported', client: 'system.cache' },
    { path: '/links', methods: ['GET'], status: 'supported', client: 'client.links' },
    { path: '/links/ping', methods: ['GET'], status: 'supported', client: 'client.linksPing' },
    { path: '/links/connect', methods: ['POST'], status: 'supported', client: 'client.linksConnect' },
    { path: '/links/disconnect', methods: ['POST'], status: 'supported', client: 'client.linksDisconnect' },
    { path: '/flush', methods: ['POST'], status: 'supported', client: 'client.flush' },
    { path: '/collections/distributed', methods: ['GET'], status: 'supported', client: 'client.listCollectionsDistributed' },
    { path: '/collections', methods: ['GET', 'POST'], status: 'supported', client: 'collections.list/create' },
    { path: '/collections/{name}', methods: ['GET', 'DELETE'], status: 'supported', client: 'collections.get/delete' },
    { path: '/collections/{name}/lang', methods: ['GET'], status: 'supported', client: 'collections.language' },
    { path: '/collections/{name}/aliases', methods: ['GET'], status: 'supported', client: 'aliases.listCollection' },
    { path: '/collections/{name}/update', methods: ['POST'], status: 'supported', client: 'collections.update' },
    { path: '/collections/{name}/documents', methods: ['GET', 'POST', 'DELETE'], status: 'supported', client: 'documents.list/add/deleteByFilter' },
    { path: '/collections/{name}/documents/import', methods: ['POST'], status: 'supported', client: 'documents.import' },
    { path: '/collections/{name}/documents/{id}', methods: ['GET', 'PUT', 'DELETE'], status: 'supported', client: 'documents.get/update/delete' },
    { path: '/collections/{name}/documents/{id}/context', methods: ['GET'], status: 'supported', client: 'documents.context' },
    { path: '/collections/{name}/documents/maybe', methods: ['GET', 'POST'], status: 'supported', client: 'documents.maybe' },
    { path: '/collections/{name}/documents/_update_by_query', methods: ['POST'], status: 'supported', client: 'documents.updateByQuery' },
    { path: '/collections/{name}/documents/_delete_by_query', methods: ['POST'], status: 'supported', client: 'documents.deleteByQuery' },
    { path: '/collections/{name}/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.search' },
    { path: '/collections/{name}/documents/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.searchLegacy' },
    { path: '/collections/{name}/vector_search', methods: ['GET', 'POST'], status: 'supported', client: 'search.vectorSearch' },
    { path: '/multi_search', methods: ['GET', 'POST'], status: 'supported', client: 'search.multiSearch' },
    { path: '/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.globalSearch/searchAll' },
    { path: '/sql', methods: ['GET', 'POST'], status: 'supported', client: 'system.sql/execSql' },
    { path: '/collections/{name}/documents/facet_counts', methods: ['GET', 'POST'], status: 'supported', client: 'documents.facetCounts' },
    { path: '/collections/{name}/documents/export', methods: ['GET', 'POST'], status: 'supported', client: 'documents.export' },
    { path: '/collections/{name}/synonyms', methods: ['GET'], status: 'supported', client: 'synonyms.list' },
    { path: '/collections/{name}/synonyms/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'synonyms.get/create/update/delete' },
    { path: '/collections/{name}/synonym_sets', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; synonyms.list uses /collections/{name}/synonyms.' },
    { path: '/collections/{name}/synonym_sets/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'omitted', reason: 'Compatibility alias; synonym item methods use /collections/{name}/synonyms/{id}.' },
    { path: '/synonyms', methods: ['GET'], status: 'supported', client: 'synonyms.listAll' },
    { path: '/synonyms/global', methods: ['GET'], status: 'supported', client: 'synonyms.listGlobal' },
    { path: '/synonyms/global/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'synonyms.getGlobal/createGlobal/updateGlobal/deleteGlobal' },
    { path: '/synonym_sets', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; synonyms.listAll uses /synonyms.' },
    { path: '/synonym_sets/global', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; synonyms.listGlobal uses /synonyms/global.' },
    { path: '/synonym_sets/global/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'omitted', reason: 'Compatibility alias; global synonym methods use /synonyms/global/{id}.' },
    { path: '/synonym_sets/global/items/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'omitted', reason: 'Compatibility alias; global synonym methods use /synonyms/global/{id}.' },
    { path: '/collections/{name}/stopwords', methods: ['GET', 'POST'], status: 'supported', client: 'stopwords.list/create' },
    { path: '/collections/{name}/stopwords/{word}', methods: ['DELETE'], status: 'supported', client: 'stopwords.delete' },
    { path: '/collections/{name}/stopword_sets', methods: ['GET', 'POST'], status: 'omitted', reason: 'Compatibility alias; stopword methods use /collections/{name}/stopwords.' },
    { path: '/collections/{name}/stopword_sets/{word}', methods: ['DELETE'], status: 'omitted', reason: 'Compatibility alias; stopwords.delete uses /collections/{name}/stopwords/{word}.' },
    { path: '/stopwords', methods: ['GET'], status: 'supported', client: 'stopwords.listAll' },
    { path: '/stopwords/global', methods: ['GET', 'POST'], status: 'supported', client: 'stopwords.listGlobal/createGlobal' },
    { path: '/stopwords/global/{word}', methods: ['DELETE'], status: 'supported', client: 'stopwords.deleteGlobal' },
    { path: '/stopword_sets', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; stopwords.listAll uses /stopwords.' },
    { path: '/stopword_sets/global', methods: ['GET', 'POST'], status: 'omitted', reason: 'Compatibility alias; global stopword methods use /stopwords/global.' },
    { path: '/stopword_sets/global/{word}', methods: ['DELETE'], status: 'omitted', reason: 'Compatibility alias; stopwords.deleteGlobal uses /stopwords/global/{word}.' },
    { path: '/stopword_sets/global/items/{word}', methods: ['DELETE'], status: 'omitted', reason: 'Compatibility alias; stopwords.deleteGlobal uses /stopwords/global/{word}.' },
    { path: '/collections/{name}/overrides', methods: ['GET'], status: 'supported', client: 'overrides.list' },
    { path: '/collections/{name}/overrides/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'overrides.get/create/update/delete' },
    { path: '/collections/{name}/curations', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; overrides.list uses /collections/{name}/overrides.' },
    { path: '/collections/{name}/curations/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'omitted', reason: 'Compatibility alias; override item methods use /collections/{name}/overrides/{id}.' },
    { path: '/collections/{name}/curation_sets', methods: ['GET'], status: 'omitted', reason: 'Compatibility alias; overrides.list uses /collections/{name}/overrides.' },
    { path: '/collections/{name}/curation_sets/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'omitted', reason: 'Compatibility alias; override item methods use /collections/{name}/overrides/{id}.' },
    { path: '/aliases', methods: ['GET'], status: 'supported', client: 'aliases.list' },
    { path: '/aliases/{name}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'aliases.get/create/update/delete' },
    { path: '/keys', methods: ['GET', 'POST'], status: 'supported', client: 'keys.list/create' },
    { path: '/keys/{id}', methods: ['GET', 'PUT', 'DELETE'], status: 'supported', client: 'keys.get/update/delete' },
    { path: '/users', methods: ['GET', 'POST'], status: 'supported', client: 'users.list/create' },
    { path: '/users/{name}', methods: ['GET', 'PUT', 'DELETE'], status: 'supported', client: 'users.get/update/delete' },
    { path: '/analytics/click', methods: ['POST'], status: 'supported', client: 'analytics.click' },
    { path: '/update-counters', methods: ['GET', 'POST'], status: 'supported', client: 'system.updateCounters' },
    { path: '/debug/counters', methods: ['GET'], status: 'supported', client: 'system.debugCounters' },
    { path: '/query', methods: ['GET'], status: 'omitted', reason: 'Alias of /status; client exposes status() instead of duplicate naming.' },
    { path: '/search-config', methods: ['GET'], status: 'supported', client: 'system.searchConfig' },
    { path: '/ready', methods: ['GET'], status: 'supported', client: 'system.ready' },
    { path: '/repair', methods: ['GET', 'POST'], status: 'supported', client: 'system.repair' },
    { path: '/presets', methods: ['GET'], status: 'supported', client: 'presets.list' },
    { path: '/presets/{name}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'presets.get/create/update/delete' },
    { path: '/modules', methods: ['GET'], status: 'supported', client: 'modules.list' },
    { path: '/modules/load', methods: ['POST'], status: 'omitted', reason: 'Prefix alias; modules.load(name) uses the explicit /loadmodule/{name} form.' },
    { path: '/modules/unload', methods: ['POST'], status: 'omitted', reason: 'Prefix alias; modules.unload(name) uses the explicit /unloadmodule/{name} form.' },
    { path: '/loadmodule', methods: ['POST'], status: 'omitted', reason: 'Body-based alias; modules.load(name) uses the explicit /loadmodule/{name} form.' },
    { path: '/loadmodule/{name}', methods: ['POST'], status: 'supported', client: 'modules.load' },
    { path: '/unloadmodule', methods: ['POST'], status: 'omitted', reason: 'Body-based alias; modules.unload(name) uses the explicit /unloadmodule/{name} form.' },
    { path: '/unloadmodule/{name}', methods: ['POST'], status: 'supported', client: 'modules.unload' },
    { path: '/modules/{name}', methods: ['ANY'], status: 'supported', client: 'modules.call' },
    { path: '/modules/{name}/syntax', methods: ['GET'], status: 'supported', client: 'modules.syntax' }
];

module.exports = {
    NODE_CLIENT_ROUTE_COVERAGE
};
