/**
 * hlquery Node.js Client - Server conformance manifest
 *
 * This manifest maps routed server endpoints to the Node client wrapper that
 * owns them. Any server route in scope must be marked as supported or omitted.
 */

const NODE_CLIENT_ROUTE_COVERAGE = [
    { path: '/', methods: ['GET'], status: 'supported', client: 'system.info' },
    { path: '/health', methods: ['GET'], status: 'supported', client: 'system.health' },
    { path: '/status', methods: ['GET'], status: 'supported', client: 'system.status' },
    { path: '/startup', methods: ['GET'], status: 'supported', client: 'system.startup' },
    { path: '/boot-status', methods: ['GET'], status: 'supported', client: 'system.bootStatus' },
    { path: '/stats', methods: ['GET'], status: 'supported', client: 'system.stats' },
    { path: '/metrics', methods: ['GET'], status: 'supported', client: 'system.metrics' },
    { path: '/metrics.json', methods: ['GET'], status: 'supported', client: 'system.metricsJson' },
    { path: '/connections', methods: ['GET'], status: 'supported', client: 'system.connections' },
    { path: '/rocksdb', methods: ['GET'], status: 'supported', client: 'system.rocksdb' },
    { path: '/_rocksdb', methods: ['GET'], status: 'supported', client: 'system.rocksdbInternal' },
    { path: '/doctotal', methods: ['GET'], status: 'supported', client: 'system.docTotal' },
    { path: '/etc', methods: ['GET'], status: 'supported', client: 'system.etc' },
    { path: '/ping', methods: ['GET'], status: 'supported', client: 'system.ping' },
    { path: '/integrity', methods: ['GET'], status: 'supported', client: 'system.integrity' },
    { path: '/consistency', methods: ['GET'], status: 'supported', client: 'system.consistency' },
    { path: '/self-check', methods: ['GET'], status: 'supported', client: 'system.selfCheck' },
    { path: '/admin/storage_status', methods: ['GET'], status: 'supported', client: 'system.storageStatus' },
    { path: '/cluster/health', methods: ['GET'], status: 'supported', client: 'client.clusterHealth' },
    { path: '/cluster/stats', methods: ['GET'], status: 'supported', client: 'client.clusterStats' },
    { path: '/cluster/nodes', methods: ['GET'], status: 'supported', client: 'client.clusterNodes' },
    { path: '/links', methods: ['GET'], status: 'supported', client: 'client.links' },
    { path: '/links/ping', methods: ['GET'], status: 'supported', client: 'client.linksPing' },
    { path: '/links/connect', methods: ['POST'], status: 'supported', client: 'client.linksConnect' },
    { path: '/links/disconnect', methods: ['POST'], status: 'supported', client: 'client.linksDisconnect' },
    { path: '/flush', methods: ['POST'], status: 'supported', client: 'client.flush' },
    { path: '/collections/distributed', methods: ['GET'], status: 'supported', client: 'client.listCollectionsDistributed' },
    { path: '/collections', methods: ['GET', 'POST'], status: 'supported', client: 'collections.list/create' },
    { path: '/collections/{name}', methods: ['GET', 'DELETE'], status: 'supported', client: 'collections.get/delete' },
    { path: '/collections/{name}/update', methods: ['POST'], status: 'supported', client: 'collections.update' },
    { path: '/collections/{name}/documents', methods: ['GET', 'POST', 'DELETE'], status: 'supported', client: 'documents.list/add/deleteByFilter' },
    { path: '/collections/{name}/documents/import', methods: ['POST'], status: 'supported', client: 'documents.import' },
    { path: '/collections/{name}/documents/{id}', methods: ['GET', 'PUT', 'DELETE'], status: 'supported', client: 'documents.get/update/delete' },
    { path: '/collections/{name}/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.search' },
    { path: '/collections/{name}/documents/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.searchLegacy' },
    { path: '/collections/{name}/vector_search', methods: ['GET', 'POST'], status: 'supported', client: 'search.vectorSearch' },
    { path: '/multi_search', methods: ['GET', 'POST'], status: 'supported', client: 'search.multiSearch' },
    { path: '/search', methods: ['GET', 'POST'], status: 'supported', client: 'search.globalSearch' },
    { path: '/sql', methods: ['GET', 'POST'], status: 'supported', client: 'system.sql/execSql' },
    { path: '/sam/rebuild', methods: ['POST'], status: 'supported', client: 'sam.rebuild' },
    { path: '/sam/search', methods: ['GET'], status: 'supported', client: 'sam.search' },
    { path: '/sam/status', methods: ['GET'], status: 'supported', client: 'sam.status' },
    { path: '/sam/debug', methods: ['GET'], status: 'supported', client: 'sam.debug' },
    { path: '/sam/history', methods: ['GET'], status: 'supported', client: 'sam.history' },
    { path: '/sam/pause', methods: ['POST'], status: 'supported', client: 'sam.pause/clearPause' },
    { path: '/sam/documents', methods: ['GET'], status: 'supported', client: 'sam.listDocuments' },
    { path: '/sam/documents/{collection}/{id}', methods: ['GET'], status: 'supported', client: 'sam.getDocument/openDocument' },
    { path: '/collections/{name}/documents/facet_counts', methods: ['GET', 'POST'], status: 'supported', client: 'documents.facetCounts' },
    { path: '/collections/{name}/documents/export', methods: ['GET', 'POST'], status: 'supported', client: 'documents.export' },
    { path: '/collections/{name}/synonyms', methods: ['GET'], status: 'supported', client: 'synonyms.list' },
    { path: '/collections/{name}/synonyms/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'synonyms.get/create/update/delete' },
    { path: '/synonyms', methods: ['GET'], status: 'supported', client: 'synonyms.listAll' },
    { path: '/synonyms/global', methods: ['GET'], status: 'supported', client: 'synonyms.listGlobal' },
    { path: '/synonyms/global/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'synonyms.getGlobal/createGlobal/updateGlobal/deleteGlobal' },
    { path: '/collections/{name}/stopwords', methods: ['GET', 'POST'], status: 'supported', client: 'stopwords.list/create' },
    { path: '/collections/{name}/stopwords/{word}', methods: ['DELETE'], status: 'supported', client: 'stopwords.delete' },
    { path: '/stopwords', methods: ['GET'], status: 'supported', client: 'stopwords.listAll' },
    { path: '/stopwords/global', methods: ['GET', 'POST'], status: 'supported', client: 'stopwords.listGlobal/createGlobal' },
    { path: '/stopwords/global/{word}', methods: ['DELETE'], status: 'supported', client: 'stopwords.deleteGlobal' },
    { path: '/collections/{name}/overrides', methods: ['GET'], status: 'supported', client: 'overrides.list' },
    { path: '/collections/{name}/overrides/{id}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'overrides.get/create/update/delete' },
    { path: '/aliases', methods: ['GET'], status: 'supported', client: 'aliases.list' },
    { path: '/aliases/{name}', methods: ['GET', 'POST', 'PUT', 'DELETE'], status: 'supported', client: 'aliases.get/create/update/delete' },
    { path: '/keys', methods: ['GET', 'POST'], status: 'supported', client: 'keys.list/create' },
    { path: '/keys/{id}', methods: ['GET', 'PUT', 'DELETE'], status: 'supported', client: 'keys.get/update/delete' },
    { path: '/update-counters', methods: ['GET', 'POST'], status: 'omitted', reason: 'Internal maintenance endpoint; intentionally left off the public Node client.' },
    { path: '/query', methods: ['GET'], status: 'omitted', reason: 'Alias of /status; client exposes status() instead of duplicate naming.' },
    { path: '/search-config', methods: ['GET'], status: 'omitted', reason: 'Diagnostic configuration endpoint; stable client exposes raw executeRequest() for this route.' },
    { path: '/ready', methods: ['GET'], status: 'omitted', reason: 'Readiness alias; client exposes startup() and bootStatus() instead of duplicate naming.' },
    { path: '/llm', methods: ['GET', 'POST'], status: 'omitted', reason: 'LLM runtime endpoint is module/config dependent and not part of the stable SDK surface yet.' },
    { path: '/repair', methods: ['POST'], status: 'omitted', reason: 'Administrative repair endpoint; intentionally left off the public Node client.' },
    { path: '/modules', methods: ['GET'], status: 'supported', client: 'modules.list' },
    { path: '/modules/{name}', methods: ['ANY'], status: 'supported', client: 'modules.call' },
    { path: '/modules/{name}/syntax', methods: ['GET'], status: 'supported', client: 'modules.syntax' }
];

module.exports = {
    NODE_CLIENT_ROUTE_COVERAGE
};
